// automatically generated by the FlatBuffers compiler, do not modify


// @generated
extern crate flatbuffers;


#[allow(unused_imports, dead_code)]
pub mod screen_io_t {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

// struct Message, aligned to 1
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Message(pub [u8; 1056]);
impl Default for Message { 
  fn default() -> Self { 
    Self([0; 1056])
  }
}
impl core::fmt::Debug for Message {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Message")
      .field("app", &self.app())
      .field("payload", &self.payload())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Message {}
impl<'a> flatbuffers::Follow<'a> for Message {
  type Inner = &'a Message;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Message>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Message {
  type Inner = &'a Message;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Message>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Message {
    type Output = Message;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const Message as *const u8, <Self as flatbuffers::Push>::size());
        dst.copy_from_slice(src);
    }
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(1)
    }
}

impl<'a> flatbuffers::Verifiable for Message {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Message {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    app: &[u8; 32],
    payload: &[u8; 1024],
  ) -> Self {
    let mut s = Self([0; 1056]);
    s.set_app(app);
    s.set_payload(payload);
    s
  }

  pub fn app(&'a self) -> flatbuffers::Array<'a, u8, 32> {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    unsafe { flatbuffers::Array::follow(&self.0, 0) }
  }

  pub fn set_app(&mut self, items: &[u8; 32]) {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    unsafe { flatbuffers::emplace_scalar_array(&mut self.0, 0, items) };
  }

  pub fn payload(&'a self) -> flatbuffers::Array<'a, u8, 1024> {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    unsafe { flatbuffers::Array::follow(&self.0, 32) }
  }

  pub fn set_payload(&mut self, items: &[u8; 1024]) {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid array in this slot
    unsafe { flatbuffers::emplace_scalar_array(&mut self.0, 32, items) };
  }

}

}  // pub mod ScreenIoT

